version: "3.8"

services:
  jwt:
    container_name: jwt
    build:
      context: ./jwt
    env_file:
      - ./jwt/.env
    ports:
      - 5002:5002
    volumes:
      - ./jwt:/jwt

  url:
    container_name: url
    build:
      context: ./url
    env_file:
      - ./url/.env
    ports:
      - 5001:5001
    volumes:
      - ./url:/url
    depends_on:
      - psql
      - user

  user:
    container_name: user
    build:
      context: ./user
    env_file:
      - ./user/.env
    ports:
      - 5000:5000
    volumes:
      - ./user:/user
      - type: bind
        source: ./user
        target: /user
    depends_on:
      - psql
  
  psql:
    container_name: psql
    image: "postgres:14.1-alpine"
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=postgresadmin
      - POSTGRES_PASSWORD=password
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: