apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-initdb-config
  namespace: shortener-app
  labels:
    app: postgres
data:
  initdb.sql: |
    CREATE TABLE users (
      id SERIAL PRIMARY KEY,
      username VARCHAR (50) UNIQUE NOT NULL,
      password VARCHAR NOT NULL
    );

    CREATE TABLE IF NOT EXISTS urls (
        id SERIAL PRIMARY KEY,
        original VARCHAR NOT NULL,
        short VARCHAR (50) UNIQUE NOT NULL,
        username VARCHAR (50) NOT NULL,
        FOREIGN KEY (username)
            REFERENCES users(username)
    );
