kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv-volume
  namespace: shortener-app
  labels:
    type: local
    app: postgres
spec:
  storageClassName: microk8s-hostpath
  capacity:
    storage: 100M
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/opt/postgres/data/"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim
  namespace: shortener-app
  labels:
    app: postgres
spec:
  storageClassName: microk8s-hostpath
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100M