apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: shortener-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - kubeclass-187
                - kubeclass-188
      containers:
        - name: postgres-container
          image: postgres:14.1-alpine
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d
              name: initdb
            # - mountPath: /var/lib/postgresql/data
            #   name: db
      volumes:
        - name: initdb
          persistentVolumeClaim:
            claimName: mysql-initdb-pv-claim
        # - name: db
        #   persistentVolumeClaim:
        #     claimName: postgres-pv-claim