version: "3.8"

services:
  url:
    container_name: url
    build:
      context: ./url
    env_file:
      - ./url/.env
    expose:
      - 5001
    volumes:
      - ./url:/url
    depends_on:
      - psql
      - user

  user:
    container_name: user
    build:
      context: ./user
    env_file:
      - ./user/.env
    expose:
      - 5000
    volumes:
      - ./user:/user
      - type: bind
        source: ./user
        target: /user
    depends_on:
      - psql
  
  psql:
    container_name: psql
    image: "postgres:14.1-alpine"
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=postgresadmin
      - POSTGRES_PASSWORD=password
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
      - postgres_data:/var/lib/postgresql/data

  nginx:
    container_name: nginx
    build:
      context: ./nginx
    ports:
      - 80:80
    depends_on:
      - user

volumes:
  postgres_data: