apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-api-deployment
  namespace: shortener-app
  labels:
    app: user-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user-api
  template:
    metadata:
      labels:
        app: user-api
    spec:
      containers:
      - name: user-api-container
        image: localhost:32000/user-api:v1
        ports:
        - containerPort: 5000
        # command: ["sh", "-c", "sleep 10; pipenv run python manage.py migrate && pipenv run python manage.py runserver 0.0.0.0:8000"]
        envFrom:
          - configMapRef:
              name: api-config
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: POSTGRES_PASSWORD