apiVersion: v1
kind: Service
metadata:
  name: user-api-service
  namespace: shortener-app
spec:
  type: ClusterIP
  ports:
   - protocol: TCP
     port: 5000
     targetPort: 5000
  selector:
    app: user-api